export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const LOADING = "LOADING";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_TEACHER_SUCCESS = "LOGIN_TEACHER_SUCCESS";
export const FETCH_TEACHER_SUCCESS = "FETCH_TEACHER_SUCCESS";

export const INCREMENT_PAGE = "INCREMENT_PAGE";
export const DECREMENT_PAGE = "DECREMENT_PAGE";
